spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    dispatch-options-request: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
  profiles:
    group:
      local: "local-envs,local-db"
      dev: "dev-envs, dev-db"
      production: ""
    active: dev

  # kafka 설정
  kafka:
    bootstrap-servers: 127.0.0.1:29092 #, 127.0.0.1:29093, 127.0.0.1:29094
    consumer:
      group-id: my-group
      auto-offset-reset: earliest

security:
  jwt:
    key-value: ${SECURITY_JWT_KEY}
  crypto-db-iv: ${SECURITY_CRYPTO_IV} # 256 bit
  crypto-db-key: ${SECURITY_CRYPTO_KEY} # 256 bit


# Exchange Rate API
exchange:
  host: "www.koreaexim.go.kr"
  path: "site/program/financial/exchangeJSON"
  authkey: ${EXCHANGE_AUTHKEY}
  type: "AP01"

coolsms:
  sender: ${SMS_SENDER}
  provider: https://api.coolsms.co.kr
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}

---
# local env
spring.config.activate.on-profile: local-envs
server:
  port: 8080

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOC_DATASOURCE_URL}
    username: ${LOC_DATASOURCE_USERNAME}
    password: ${LOC_DATASOURCE_PASSWORD}

---
# dev env
spring.config.activate.on-profile: dev-envs
server:
  port: 8082

---

# dev db
spring.config.activate.on-profile: dev-db

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}


