spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    dispatch-options-request: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
  profiles:
    group:
      local: "local-envs,local-db"
      dev: "dev-envs, dev-db"
      production: ""
    active: dev

security:
  x-api-key: ${X_API_KEY}
  jwt:
    key-value: ${SECURITY_JWT_KEY}
  crypto-db-iv: ${SECURITY_CRYPTO_IV} # 256 bit
  crypto-db-key: ${SECURITY_CRYPTO_KEY} # 256 bit

# test
# Exchange Rate API
exchange:
  host: "www.koreaexim.go.kr"
  path: "site/program/financial/exchangeJSON"
  authkey: ${EXCHANGE_AUTHKEY}
  type: "AP01"

coolsms:
  sender: ${SMS_SENDER}
  provider: https://api.coolsms.co.kr
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}

---
# local env
spring.config.activate.on-profile: local-envs
server:
  port: 8083

# kafka 설정
# localhost:9091 을 쓰고 싶으면(docker로 배포 된 거 말고 로컬에서 돌릴라면) kafka compose 파일 아래처럼 수정해야함
# KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
# 도커 내부에서 돌리고 싶으면 아래와 같이 수정
#KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://kafka1:9091
#kafka:
#  bootstrap-servers: kafka1:9091,kafka2:9092,kafka3:9093
#  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOC_DATASOURCE_URL}
    username: ${LOC_DATASOURCE_USERNAME}
    password: ${LOC_DATASOURCE_PASSWORD}

kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
---
# dev env
spring.config.activate.on-profile: dev-envs
server:
  port: 8082

# kafka 설정
kafka:
  bootstrap-servers: kafka1:9091,kafka2:9092,kafka3:9093

---

# dev db
spring.config.activate.on-profile: dev-db

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}


