---
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  mvc:
    dispatch-options-request: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
  profiles:
    group:
      local: "local-envs,local-db"
      dev: "local-envs"
      production: ""
    active: local

security:
  jwt:
    key-value: "2AA4B45D5FB9FF29B722A57E3E9FAAF4F2DC33326953338C5F9B92783E"

# Exchange Rate API
exchange:
  host: "www.koreaexim.go.kr"
  path: "site/program/financial/exchangeJSON"
  authkey: "x4aRpxsOtaWnsG2EipVpwkSJZsS4vrGs"
  type: "AP01"

---
# local env
spring.config.activate.on-profile: local-envs

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://127.0.0.1:3306/MY_EXCHANGE?serverTimezone=UTC&characterEncoding=UTF-8"
      username: "root"
      password: "nextage2020!"


